---
title: "Gene enrichment analysis"
author: "Yufei Jin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(clusterProfiler)
organism = "org.Mm.eg.db"
#BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)
library(ggplot2)
```


```{r}
deg = readRDS("F:/Sag/Step4/deg")
```

```{r}
threshold = read.csv("F:/Sag/Step4/threshold.csv",row.names = 1)
peak = read.csv("F:/Sag/Step4/peak.csv",row.names = 1)
ratio = read.csv("F:/Sag/Step4/ratio.csv",row.names = 1)
Vrest = read.csv("F:/Sag/Step4/Vrest.csv",row.names = 1)
trough = read.csv("F:/Sag/Step4/trough.csv",row.names = 1)
frequency = read.csv("F:/Sag/Step4/frequency.csv",row.names = 1)
```

```{r}
gene_list = intersect(rownames(frequency),deg)
```


```{r}
enter_id = bitr(gene_list, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = organism,drop = T)$ENTREZID
```


```{r}
go_enrich <- enrichGO(gene = enter_id,
                      OrgDb = organism, 
                      keyType = 'ENTREZID',
                      readable = T,
                      ont = "BP",
                      pAdjustMethod = "BH",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.05)
```

```{r}
p = dotplot(go_enrich,x="Count",size="Count", font.size=10) + ggtitle("Pvalb vs Other cell types")
ggsave("deg.png", p, width = 5, height = 8, dpi = 300)
```
